#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

if uci -q get system.@imm_init[0].opkg_mirror > "/dev/null"; then
	uci -q batch <<-EOF
		rename system.@imm_init[0].opkg_mirror="apk_mirror"
		commit system
	EOF
fi

apk_mirror="$(uci -q get system.@imm_init[0].apk_mirror)"
case "$apk_mirror" in
	""|"https://mirrors.vsean.net/openwrt")
		apk_mirror="https://mirrors.vsean.net/immortalwrt"
		uci -q batch <<-EOF
			set system.@imm_init[0].apk_mirror="$apk_mirror"
			commit system
		EOF
		;;
esac

apk_mirror_sed="$(printf '%s\n' "$apk_mirror" | sed 's/[\\&,]/\\&/g')"
sed -i.bak \
	-e "s,https://downloads.immortalwrt.org,$apk_mirror_sed,g" \
	-e "s,https://mirrors.vsean.net/openwrt,$apk_mirror_sed,g" \
	"/etc/apk/repositories.d/distfeeds.list"

exit 0
